# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


target 'RX_Swift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RX_Swift
	
  source 'https://github.com/CocoaPods/Specs.git'
  target 'RX_SwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RX_SwiftUITests' do
    # Pods for testing
  end


    pod 'RxSwift', '~> 5'
    pod 'RxCocoa', '~> 5'

end
